[workspace]
resolver = "2"
members = [
  "crates/ac-power",
  "crates/analyze",
  "crates/ask-password",
  "crates/backlight",
  "crates/binfmt",
  "crates/bootctl",
  "crates/bsod",
  "crates/cat",
  "crates/cgls",
  "crates/cgtop",
  "crates/coredump",
  "crates/coredumpctl",
  "crates/creds",
  "crates/cryptsetup",
  "crates/delta",
  "crates/detect-virt",
  "crates/difftest",
  "crates/difftest-macros",
  "crates/dissect",
  "crates/escape",
  "crates/firstboot",
  "crates/homectl",
  "crates/homed",
  "crates/hostnamectl",
  "crates/hostnamed",
  "crates/id128",
  "crates/inhibit",
  "crates/integritysetup",
  "crates/journal-gatewayd",
  "crates/journal-remote",
  "crates/journal-upload",
  "crates/journalctl",
  "crates/journald",
  "crates/libsystemd",
  "crates/localectl",
  "crates/localed",
  "crates/loginctl",
  "crates/logind",
  "crates/machine-id-setup",
  "crates/machinectl",
  "crates/machined",
  "crates/modules-load",
  "crates/mount",
  "crates/network-generator",
  "crates/networkctl",
  "crates/networkd",
  "crates/networkd-wait-online",
  "crates/notify",
  "crates/nspawn",
  "crates/oomctl",
  "crates/oomd",
  "crates/pam-systemd",
  "crates/path",
  "crates/portablectl",
  "crates/portabled",
  "crates/pstore",
  "crates/random-seed",
  "crates/repart",
  "crates/resolvectl",
  "crates/resolved",
  "crates/rfkill",
  "crates/run",
  "crates/shutdown",
  "crates/sleep",
  "crates/socket-activate",
  "crates/sysctl",
  "crates/sysext",
  "crates/systemctl",
  "crates/systemd",
  "crates/sysusers",
  "crates/test-journal-append",
  "crates/timedatectl",
  "crates/timedated",
  "crates/timesyncd",
  "crates/tmpfiles",
  "crates/tty-ask-password-agent",
  "crates/udevadm",
  "crates/udevd",
  "crates/update-done",
  "crates/user-sessions",
  "crates/varlinkctl",
  "crates/vconsole-setup",
  "crates/veritysetup",
]
exclude = ["crates/sd-boot", "crates/sd-stub"]
