[package]
name = "systemd-journald"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[[bin]]
name = "systemd-journald"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
libsystemd = { path = "../libsystemd" }
log = "0.4"
nix = { version = "0.31", features = [
  "fs",
  "poll",
  "process",
  "signal",
  "socket",
  "uio",
  "user",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
