#!/usr/bin/env python3
"""Regenerate seccomp_filter_sets.rs.

Extracts systemd's `@group` syscall sets (from src/shared/seccomp-util.c's
`syscall_filter_sets[]`) and the x86_64 syscall numbers (from a linux-headers
`asm/unistd_64.h`) into the rust data module used by SystemCallFilter=.

Sources are resolved from the pinned nixpkgs (the same systemd the port builds
against). x86_64 syscall numbers are ABI-stable, so a systemd bump only changes
the @group sets. Run:

    python3 gen_seccomp_filter_sets.py > seccomp_filter_sets.rs
"""
import glob
import re
import subprocess
import sys


def systemd_seccomp_util():
    src = subprocess.check_output(
        ["nix", "eval", "--raw", "nixpkgs#systemd.src"]
    ).decode()
    return src + "/src/shared/seccomp-util.c"


def unistd_64_h():
    # Any linux-headers asm/unistd_64.h works: existing x86_64 syscall numbers
    # never change. Prefer the nix-store copy so this is hermetic.
    for p in sorted(glob.glob("/nix/store/*linux-headers*/include/asm/unistd_64.h")):
        return p
    sys.exit("no linux-headers asm/unistd_64.h found in /nix/store; nix-build one")


def main():
    nrs = {}
    for line in open(unistd_64_h()):
        m = re.match(r"#define __NR_(\w+)\s+(\d+)\s*$", line.strip())
        if m:
            nrs[m.group(1)] = int(m.group(2))

    text = open(systemd_seccomp_util()).read()
    start = text.index("const SyscallFilterSet syscall_filter_sets")
    body = text[start : text.index("\n};", start)]
    groups = []
    for b in re.split(r"\[SYSCALL_FILTER_SET_[A-Z0-9_]+\]\s*=\s*\{", body)[1:]:
        nm = re.search(r'\.name\s*=\s*"([^"]+)"', b)
        if not nm:
            continue
        tokens = []
        vi = b.find(".value")
        if vi >= 0:
            vpart = b[vi:]
            brace = vpart.find("},")
            if brace >= 0:
                vpart = vpart[:brace]
            for s in re.findall(r'"([^"]*)"', vpart):
                tok = s.replace("\\0", "").strip()
                if tok:
                    tokens.append(tok)
        groups.append((nm.group(1), tokens))

    out = []
    w = out.append
    w("// @generated by gen_seccomp_filter_sets.py. Do not edit by hand.")
    w("// Extracted from systemd's src/shared/seccomp-util.c (the syscall_filter_sets[]")
    w("// @group table) and the x86_64 asm/unistd_64.h syscall numbers. Regenerate with")
    w("// `python3 gen_seccomp_filter_sets.py > seccomp_filter_sets.rs` after a systemd")
    w("// bump. x86_64 syscall numbers are ABI-stable, so only the @group sets change.")
    w("//! x86_64 syscall-number table and systemd @group syscall-set")
    w("//! definitions for SystemCallFilter=. See systemd seccomp-util.c.")
    w("")
    w("/// Resolve a syscall name to its x86_64 number.")
    w("pub(super) fn syscall_nr(name: &str) -> Option<i64> {")
    w("    let nr: i64 = match name {")
    for name in sorted(nrs, key=lambda k: nrs[k]):
        w(f'        "{name}" => {nrs[name]},')
    w("        _ => return None,")
    w("    };")
    w("    Some(nr)")
    w("}")
    w("")
    w("/// Resolve a systemd `@group` name (without the leading `@`) to its list of")
    w("/// member tokens (syscall names and nested `@group` references).")
    w("pub(super) fn syscall_group(name: &str) -> Option<&'static [&'static str]> {")
    w("    let set: &'static [&'static str] = match name {")
    for name, toks in groups:
        key = name[1:] if name.startswith("@") else name
        arr = ", ".join(f'"{t}"' for t in toks)
        w(f'        "{key}" => &[{arr}],')
    w("        _ => return None,")
    w("    };")
    w("    Some(set)")
    w("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
