[package]
name = "libsystemd"
version = "0.1.0"
authors = ["Niclas Overby <niclas@overby.me>"]
edition = "2024"

[dependencies]
aes-gcm = "0.10"
base64 = "0.22"
chrono = "0.4"
fern = "0.7"
libc = "0.2"
log = "0.4"
nix = { version = "0.31", features = [
  "event",
  "fs",
  "hostname",
  "inotify",
  "mount",
  "poll",
  "process",
  "signal",
  "socket",
  "user",
] }
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
signal-hook = "0.4"
threadpool = "1.8"
vpick-core = { path = "../vpick-core" }

clap = { version = "4.5", features = ["derive"] }
lz4_flex = "0.11"
lzma-rs = "0.3"
shlex = "1.3"
shmemfdrs = "0.1"
which = "8.0"
zbus = { version = "5", optional = true }
zstd = "0.13"

[dev-dependencies]
tempfile = "3"

[features]
cgroups = []
dbus_support = ["zbus"]
linux_eventfd = []
